### ISSUE TITLE
Ufak tefek yazım hatası düzeltmeleri

### ISSUE THREAD

**Issue by anilsenay** [orcuntuna/react-turkce-kaynak#2]
**Dökümanın genelinde yapılabilecek düzeltmeler:**
javascript ->  JavaScript
ide -> IDE
react -> React
css -> CSS

**Gözüme takılan yazım hataları:**
React Nedir? kısmında bulunan "güncellenerek" kelimesi -> güncellenecek
Bileşenler kısmında "sayesede" -> sayede
13. sayfada Javascript -> JavaScript, değilde -> değilse
14. sayfa kaynaklanın -> kaynaklanan, html -> HTML, Html -> HTML, paremetre -> parametre
23. sayfa müdaheleler -> müdahaleler
25. sayfa css->CSS, jsx->JSX, dom->DOM, eventelere -> eventlere

**Comment by orcuntuna** [comment]
güncellendi
